const sample=BayarStore.read().dramas.map(d=>[d.zh,d.en,d.mn,d.episodes,d.image,d.category]);
const db=BayarStore.read();
let current='overview',role='owner';const content=document.getElementById('adminContent'),modal=document.getElementById('adminDialog');const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const disabled=()=>role==='viewer'?'disabled':'';const money=n=>Number(n).toLocaleString()+' ₮';const log=text=>{db.audit.unshift({time:new Date().toLocaleString('zh-HK'),text,actor:'擁有人（示範）'});BayarStore.save(db)};
function header(title,copy,action=''){return `${role==='viewer'?'<div class="readonly-notice">目前為唯讀檢視：可以查看資料，修改操作已停用。</div>':''}<div class="admin-heading"><div><h1>${title}</h1><p>${copy}</p></div>${action}</div>`}
const table=(heads,rows)=>`<div class="table-wrap"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||'<tr><td colspan="8">暫時未有記錄</td></tr>'}</tbody></table></div>`;
function draw(){document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===current));
if(current==='overview'){content.innerHTML=header('工作空間總覽','管理短劇、邀請與定價。以下數據全部為示範。')+`<div class="stats-grid">${[['已上架短劇',db.dramas.filter(d=>d.published).length,'部示範短劇'],['成功訂單',db.orders.filter(o=>o.status==='成功').length,'示範訂單'],['成功付款總額',money(db.orders.filter(o=>o.status==='成功').reduce((s,o)=>s+o.amount,0)),'MNT · 模擬金額'],['有效邀請',db.invites.filter(i=>i.status==='可使用').length,'個示範邀請']].map(a=>`<div class="stat"><small>${a[0]}</small><strong>${a[1]}</strong><span>${a[2]}</span></div>`).join('')}</div><div class="overview-grid"><section class="admin-panel chart-panel"><h2>觀看趨勢</h2><p class="muted">示範圖表，未連接真實觀看數據</p><div class="admin-chart">${[30,52,43,71,60,84,95].map((h,i)=>`<div style="height:${h}%"><small>10/${i+1}</small></div>`).join('')}</div></section><section class="admin-panel"><h2>首發設定</h2><p class="muted">註冊：${db.prices.registration==='invite'?'邀請制':'公開註冊（候選）'}</p><p class="muted">預設免費：${db.prices.free} 集</p><p class="muted">單集解鎖：${db.prices.unlock} 金幣</p><p class="muted">網站付款：QPay</p><p class="muted">影片上傳：後期加入</p></section></div>`;}
if(current==='dramas'){content.innerHTML=header('劇庫管理','管理示範劇名、分類、免費集數及上下架。影片上傳留待正式後期開發。',`<button class="primary" data-action="add" ${disabled()}>＋ 新增示範短劇</button>`)+table(['短劇','分類','集數','免費集數','狀態','操作'],db.dramas.map(d=>`<tr><td><div class="row-title"><img src="https://images.unsplash.com/${d.image}?auto=format&fit=crop&w=100&q=70" alt=""><div>${escapeHTML(d.zh)}<small>${escapeHTML(d.mn)}</small></div></div></td><td>${escapeHTML(d.category)}</td><td>${d.episodes}</td><td>${d.free}</td><td><span class="status-pill ${d.published?'':'off'}">${d.published?'已上架':'草稿'}</span></td><td><button class="small-button" data-action="edit" data-id="${d.id}" ${disabled()}>編輯</button><button class="small-button" data-action="publish" data-id="${d.id}" ${disabled()}>${d.published?'下架':'上架'}</button></td></tr>`).join(''));}
if(current==='invites'){content.innerHTML=header('邀請管理','建立邀請碼、查看使用狀態。示範版不會發送電郵。',`<button class="primary" data-action="invite" ${disabled()}>＋ 建立邀請</button>`)+table(['受邀電郵','邀請碼','有效期','狀態','操作'],db.invites.map(i=>`<tr><td>${escapeHTML(i.email)}</td><td>${i.code}</td><td>${i.expiry}</td><td><span class="status-pill ${i.status==='可使用'?'':'off'}">${i.status}</span></td><td><button class="small-button" data-action="revoke" data-id="${i.id}" ${disabled()} ${i.status==='已撤銷'?'disabled':''}>撤銷</button></td></tr>`).join(''));}
if(current==='pricing'){const p=db.prices;const input=(name,label,min=1)=>`<label>${label}<input name="${name}" type="number" min="${min}" step="1" required value="${p[name]}" ${disabled()}></label>`;content.innerHTML=header('價格與觀看規則','所有價格顯示 MNT。修改會同步到同一瀏覽器的觀眾展示網站。')+`<form id="priceForm" class="admin-form price-form admin-panel"><h2>VIP 訂閱</h2>${input('month','月費（MNT）')}${input('quarter','季費（MNT）')}${input('year','年費（MNT）')}<p class="settings-note">預設續期為產品意向，QPay 自動扣款能力待確認。</p><h2>金幣套餐</h2>${[1,2,3,4].map(i=>input('p'+i,'套餐 '+i+' 價格（MNT）')+input('c'+i,'套餐 '+i+' 金幣（暫定示範）')).join('')}<h2>觀看與註冊</h2>${input('free','新劇預設免費集數',0)}${input('unlock','單集解鎖金幣')}<label>註冊方式<select name="registration" ${disabled()}><option value="invite" ${p.registration==='invite'?'selected':''}>邀請制</option><option value="public" ${p.registration==='public'?'selected':''}>公開註冊（後期候選）</option></select></label><p class="settings-note">免費集數設定為新劇預設，已有短劇請在劇庫編輯。訂單保留購入時價格。正式金幣數量待確認。</p><div class="full"><button class="primary" type="submit" ${disabled()}>儲存示範設定</button><p id="saveMessage" class="save-note" role="status"></p></div></form>`;}
if(current==='orders'){content.innerHTML=header('訂單記錄','此處包括前台建立的模擬付款訂單。',`<button class="secondary" data-action="export">匯出 CSV</button>`)+`<div class="filter-row"><input id="orderSearch" placeholder="搜尋訂單或電郵" aria-label="搜尋訂單"><select id="orderStatus" aria-label="訂單狀態"><option>全部狀態</option><option>成功</option><option>待付款</option></select></div><div id="orderTable"></div>`;drawOrders();}
if(current==='audit'){content.innerHTML=header('操作記錄','展示管理操作留痕。正式版需要由伺服器保存不可竄改的記錄。')+`<div class="admin-panel">${db.audit.map(a=>`<div class="audit-item"><span>${escapeHTML(a.text)}</span><small>${a.actor} · ${a.time}</small></div>`).join('')}</div>`;}}
function drawOrders(){const q=document.getElementById('orderSearch').value.toLowerCase(),status=document.getElementById('orderStatus').value;document.getElementById('orderTable').innerHTML=table(['訂單','用戶','商品','金額（MNT）','付款渠道','狀態'],db.orders.filter(o=>(o.id+' '+o.email).toLowerCase().includes(q)&&(status==='全部狀態'||o.status===status)).map(o=>`<tr><td>${o.id}<small>${o.time}</small></td><td>${o.email}</td><td>${o.product}</td><td>${money(o.amount)}</td><td>QPay（模擬）</td><td><span class="status-pill ${o.status==='成功'?'':'off'}">${o.status}</span></td></tr>`).join(''));}
function open(body){document.getElementById('adminDialogBody').innerHTML=body;modal.showModal()}
function editDrama(id){const d=db.dramas.find(d=>d.id===id)||{id:0,zh:'',en:'',mn:'',episodes:48,free:db.prices.free,category:'浪漫愛情',synopsis:''};open(`<h2>${id?'編輯短劇':'新增示範短劇'}</h2><form id="dramaForm" class="admin-form" data-id="${id||0}">${[['zh','繁中劇名'],['en','英文劇名'],['mn','蒙古語劇名']].map(([key,label])=>`<label class="full">${label}<input name="${key}" value="${escapeHTML(d[key])}" required maxlength="120"></label>`).join('')}<label>總集數<input type="number" name="episodes" value="${d.episodes}" min="1" max="200" required></label><label>免費集數<input type="number" name="free" value="${d.free}" min="0" max="200" required></label><label class="full">分類<select name="category">${['浪漫愛情','復仇逆襲','懸疑反轉','家庭故事'].map(c=>`<option ${c===d.category?'selected':''}>${c}</option>`).join('')}</select></label><label class="full">簡介<textarea name="synopsis" maxlength="1000">${escapeHTML(d.synopsis)}</textarea></label><p class="full muted">新劇使用示範封面。此階段不包含影片上傳。</p><p id="formError" class="full" role="alert"></p><button class="primary full" type="submit">儲存示範資料</button></form>`)}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-page]');if(nav){current=nav.dataset.page;draw();return}if(e.target.closest('.dialog-close')){modal.close();return}const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='export'){const csv='\uFEFF'+[['訂單','電郵','商品','MNT','狀態','時間'],...db.orders.map(o=>[o.id,o.email,o.product,o.amount,o.status,o.time])].map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download='Bayar_Demo_Orders.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return}if(role!=='owner')return;const id=+b.dataset.id;if(a==='edit'||a==='add')editDrama(id);if(a==='publish'){const d=db.dramas.find(d=>d.id===id);d.published=!d.published;log(`${d.published?'上架':'下架'}短劇：${d.zh}`);draw()}if(a==='invite')open(`<h2>建立示範邀請</h2><p>只生成後台示範記錄，不會寄出電郵，新邀請碼可在前台作模擬註冊。</p><form id="inviteForm"><label>受邀者電郵<input type="email" name="email" required placeholder="friend@example.com"></label><label>有效期<input type="date" name="expiry" required min="${new Date().toISOString().slice(0,10)}" value="${new Date(Date.now()+30*86400000).toISOString().slice(0,10)}"></label><button class="primary" type="submit">生成示範邀請碼</button></form>`);if(a==='revoke'){const i=db.invites.find(i=>i.id===id);i.status='已撤銷';log('撤銷邀請：'+i.email);draw()}});
document.addEventListener('submit',e=>{e.preventDefault();if(role!=='owner')return;const f=e.target,values=Object.fromEntries(new FormData(f));if(f.id==='dramaForm'){if(+values.free>+values.episodes){document.getElementById('formError').textContent='免費集數不可多於總集數。';return}const id=+f.dataset.id;let d=db.dramas.find(d=>d.id===id);if(!d){d={id:Math.max(...db.dramas.map(d=>d.id))+1,image:sample[0][4],published:false};db.dramas.push(d)}Object.assign(d,values,{episodes:+values.episodes,free:+values.free});log('儲存短劇：'+d.zh);modal.close();draw()}if(f.id==='inviteForm'){const code='BAYAR-DEMO-'+String(db.invites.length+1).padStart(4,'0');db.invites.unshift({id:db.invites.length+1,email:values.email,expiry:values.expiry,code,status:'可使用'});log('建立示範邀請：'+values.email);draw();document.getElementById('adminDialogBody').innerHTML=`<h2>示範邀請已建立</h2><p>${escapeHTML(values.email)}</p><div class="invite-result">${code}</div><p>請在前台使用此碼及上方電郵註冊。沒有發出任何電郵。</p>`}if(f.id==='priceForm'){for(const [k,v]of Object.entries(values))db.prices[k]=k==='registration'?v:+v;log('更新價格與觀看規則');document.getElementById('saveMessage').textContent='已儲存，前台展示價格及規則已同步。'}});
document.getElementById('role').addEventListener('change',e=>{role=e.target.value;modal.close();draw()});document.addEventListener('input',e=>{if(e.target.id==='orderSearch')drawOrders()});document.addEventListener('change',e=>{if(e.target.id==='orderStatus')drawOrders()});draw();


window.addEventListener('storage',()=>{Object.assign(db,BayarStore.read());draw()});window.addEventListener('focus',()=>{Object.assign(db,BayarStore.read());draw()});
