const text={
mn:{home:'Нүүр',browse:'Драмууд',latest:'Шинэ',login:'Нэвтрэх',exclusive:'ОНЦЛОХ ДРАМА',heroCategory:'РОМАНТИК · НУУЦ · ӨШӨӨ АВАЛТ',heroTitle:'Шөнө дундын\nамлалт',heroSummary:'Нэг гэрээ. Хоёр нууц. Хайр ба өшөө авалтын дунд тэр хэнийг сонгох вэ?',episodes:'48 анги',subtitles:'Монгол хадмал',watch:'Үнэгүй үзэх',details:'Дэлгэрэнгүй',free:'Эхний 2 анги үнэгүй',heroCaption:'БОГИНО ТҮҮХ. ИХ МЭДРЭМЖ.',discover:'Дараагийн дуртай түүхээ олоорой',discoverCopy:'Хайр, нууц, гэнэтийн эргэлт. Таны завсарлага бүрт шинэ түүх.',trending:'Эрэлттэй драмууд',week:'ЭНЭ ДОЛОО ХОНОГТ',vipTitle:'Түүх бүрийг дуустал нь.',vipCopy:'VIP эрхээр бүх ангийг үзээрэй. Зар сурталчилгаагүй, тасралтгүй.',vipButton:'VIP эрхтэй болох',new:'Шинээр нэмэгдсэн',closing:'Нэг ангиас эхэл. Шинэ түүхийг нээ.',invite:'Урилгаар нэгдэх',support:'Тусламж',privacy:'Нууцлал',terms:'Үйлчилгээний нөхцөл',demo:'Нүүр хуудасны загвар · Драмууд болон зургууд нь жишээ болно.',account:'Миний',okay:'Ойлголоо',empty:'Энэ ангилалд одоогоор драма алга.',cats:['Бүгд','Романтик','Өшөө авалт','Нууцлаг','Гэр бүл'],hot:'ЭРЭЛТТЭЙ',newBadge:'ШИНЭ',unit:'анги',dialog:'Энэ нь эхний шатны нүүр хуудасны загвар юм. Үзэх, бүртгүүлэх, төлбөр төлөх үйлдлийг дараагийн шатанд харуулна.',inviteTitle:'Урилгаар нэгдэх',vipDialog:'VIP гишүүнчлэл',vipDesc:'Сарын: 12,900 ₮ · Улирлын: 32,900 ₮ · Жилийн: 119,000 ₮. Энэ загварт төлбөр авахгүй.'},
en:{home:'Home',browse:'Browse',latest:'New releases',login:'Sign in',exclusive:'IN THE SPOTLIGHT',heroCategory:'ROMANCE · SECRETS · REVENGE',heroTitle:'A promise\nafter midnight',heroSummary:'One contract. Two secrets. Between love and revenge, whose side will she choose?',episodes:'48 episodes',subtitles:'Mongolian subtitles',watch:'Watch free',details:'View details',free:'First 2 episodes free',heroCaption:'SHORT STORIES. BIG FEELINGS.',discover:'Find your next obsession',discoverCopy:'Love, secrets, and unexpected turns. A new story for every little break.',trending:'Trending now',week:'THIS WEEK',vipTitle:'Every story. All the way.',vipCopy:'Unlock the full library with VIP. Uninterrupted stories, without ads.',vipButton:'Explore VIP',new:'Fresh stories',closing:'Start with one episode. Find a whole new story.',invite:'Join by invitation',support:'Support',privacy:'Privacy',terms:'Terms',demo:'Homepage preview · Drama titles and artwork are illustrative.',account:'Account',okay:'Got it',empty:'No dramas in this category yet.',cats:['All stories','Romance','Revenge','Mystery','Family'],hot:'TRENDING',newBadge:'NEW',unit:'episodes',dialog:'This is the first-stage homepage preview. Watching, registration, and payment journeys will be shown in the next stage.',inviteTitle:'Invitation-only access',vipDialog:'Babar VIP',vipDesc:'Monthly: 12,900 ₮ · Quarterly: 32,900 ₮ · Annual: 119,000 ₮. No payments are taken in this preview.'},
zh:{home:'首頁',browse:'探索劇庫',latest:'最新上架',login:'登入',exclusive:'本週焦點',heroCategory:'浪漫愛情 · 秘密 · 復仇',heroTitle:'午夜之後\n與你約定',heroSummary:'一紙契約，兩個秘密。在愛情與復仇之間，她會選擇站在誰的一邊？',episodes:'48 集',subtitles:'蒙古語字幕',watch:'免費觀看',details:'劇集詳情',free:'每部劇首 2 集免費觀看',heroCaption:'故事很短，心動很久。',discover:'下一個讓你停不下來的故事',discoverCopy:'愛情、秘密、意想不到的反轉。讓每一段小休，都有新故事。',trending:'人氣熱播',week:'本週精選',vipTitle:'好故事，看到最後。',vipCopy:'VIP 暢看全庫劇集，免廣告，讓精彩一路延續。',vipButton:'探索 VIP 會員',new:'最新上架',closing:'從一集開始，遇見你的下一個故事。',invite:'透過邀請加入',support:'支援中心',privacy:'私隱政策',terms:'使用條款',demo:'首頁展示版 · 劇名及圖片均為示範素材。',account:'我的',okay:'知道了',empty:'暫時未有此分類劇集。',cats:['全部劇集','浪漫愛情','復仇逆襲','懸疑反轉','家庭故事'],hot:'熱播',newBadge:'新上架',unit:'集',dialog:'目前係第一階段首頁展示。觀看、註冊同付款流程會喺下一階段展示；呢度唔會播放完整劇集或收取款項。',inviteTitle:'邀請制註冊',vipDialog:'Babar VIP 會員',vipDesc:'月費 12,900 ₮ · 季費 32,900 ₮ · 年費 119,000 ₮。本展示版不會收取款項。'}
};
const dramas=[
{titles:['Шөнө дундын амлалт','A Promise After Midnight','午夜之後與你約定'],cat:1,eps:48,img:'photo-1515886657613-9f3515b0c78f',tone:'#4c2435',badge:'hot'},
{titles:['Түүний эргэн ирэлт','Her Return','她的華麗歸來'],cat:2,eps:62,img:'photo-1534528741775-53994a69daeb',tone:'#563939',badge:'vip'},
{titles:['Нууц гэрээ','The Secret Contract','秘密契約'],cat:1,eps:56,img:'photo-1500648767791-00dcc994a43e',tone:'#293544',badge:'newBadge'},
{titles:['Алга болсон шөнө','The Missing Night','消失的那一夜'],cat:3,eps:40,img:'photo-1483985988355-763728e1935b',tone:'#304138',badge:'vip'},
{titles:['Дахин хайрлая','Love, Once Again','再一次愛上你'],cat:1,eps:36,img:'photo-1524504388940-b1c1722653e1',tone:'#5b3b34',badge:'hot'},
{titles:['Гэр бүлийн нууц','A Family of Secrets','豪門的秘密'],cat:4,eps:52,img:'photo-1519085360753-af0119f7cbe7',tone:'#373143',badge:'vip'},
{titles:['Сүүлчийн захидал','The Last Letter','最後一封情書'],cat:1,eps:44,img:'photo-1524250502761-1ac6f2e30d43',tone:'#533d30',badge:'newBadge'},
{titles:['Чимээгүй өшөө','Silent Revenge','無聲的復仇'],cat:2,eps:60,img:'photo-1506794778202-cad84cf45f1d',tone:'#2e3c3d',badge:'newBadge'}
];
let lang='zh',category=0,hero=0;const dialog=document.getElementById('previewDialog');
const safeTitle=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titleOf=d=>safeTitle(d.titles[{mn:0,en:1,zh:2}[lang]]);
function card(d,index){const t=text[lang];return `<button class="poster-card" data-drama="${dramas.indexOf(d)}" aria-label="${titleOf(d)}"><div class="poster" style="--tone:${d.tone}"><img src="https://images.unsplash.com/${d.img}?auto=format&fit=crop&w=500&q=80" alt="" loading="lazy"><span class="poster-label ${d.badge==='vip'?'vip':''}">${d.badge==='vip'?'♛ VIP':t[d.badge]}</span><span class="poster-number">${String(index+1).padStart(2,'0')}</span><span class="poster-title">${titleOf(d)}</span></div><h3 class="card-title">${titleOf(d)}</h3><span class="card-meta">${t.cats[d.cat]} · ${d.eps} ${t.unit}</span></button>`}
function render(){const t=text[lang];if(dramas[hero]?.published===false){const h=dramas.findIndex(d=>d.published!==false);if(h>=0)hero=h;}document.documentElement.lang=lang==='zh'?'zh-Hant':lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t[el.dataset.i18n]);document.querySelector('.categories').innerHTML=t.cats.map((c,i)=>`<button class="${i===category?'active':''}" data-category="${i}" aria-pressed="${i===category}">${c}</button>`).join('');const list=dramas.filter(d=>d.published!==false).slice(0,6).filter(d=>!category||d.cat===category);document.getElementById('trending').innerHTML=list.map(card).join('');document.querySelector('.empty').hidden=list.length>0;document.getElementById('newGrid').innerHTML=dramas.filter(d=>d.published!==false).slice(-6).map(card).join('');if(dramas[hero]){document.querySelector('[data-i18n="heroTitle"]').textContent=titleOf(dramas[hero]);document.querySelector('[data-i18n="episodes"]').textContent=`${dramas[hero].eps} ${t.unit}`;document.querySelector('[data-i18n="heroSummary"]').textContent=lang==='zh'?'當過去再次敲門，命運將迎來意想不到的反轉。':lang==='en'?'When the past returns, nothing will ever be the same.':'Өнгөрсөн үе эргэн ирэхэд бүх зүйл өөрчлөгдөнө.'}document.querySelectorAll('[data-hero]').forEach(el=>el.classList.toggle('selected',+el.dataset.hero===hero));}
function show(title,body){document.getElementById('dialogTitle').textContent=title;document.getElementById('dialogText').textContent=body;dialog.showModal()}
document.getElementById('language').addEventListener('change',e=>{lang=e.target.value;render()});
document.addEventListener('click',e=>{const cat=e.target.closest('[data-category]');if(cat){category=+cat.dataset.category;render()}const pager=e.target.closest('[data-hero]');if(pager){hero=+pager.dataset.hero;render()}const drama=e.target.closest('[data-drama]');if(drama)show(titleOf(dramas[+drama.dataset.drama]),text[lang].dialog);const button=e.target.closest('[data-action]');if(button){const action=button.dataset.action,t=text[lang];show(action==='vip'?t.vipDialog:action==='invite'?t.inviteTitle:action==='watch'||action==='detail'?titleOf(dramas[hero]):t[action],action==='vip'?t.vipDesc:t.dialog)}if(e.target.closest('.dialog-close,.dialog-ok'))dialog.close()});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});render();

document.getElementById('language').value='zh';


const originalRender=render;render=function(){originalRender();const d=dramas[hero];if(d&&typeof d.free==='number'){document.querySelector('[data-i18n=free]').textContent=lang==='zh'?'每部劇首 '+d.free+' 集免費觀看':d.free+' · '+text[lang].cats[0];}document.querySelector('.hero').hidden=!dramas.some(d=>d.published!==false);};

