// Demonstration state is held only in memory; no accounts or payments are real.
const ui={
zh:{back:'返回首頁',preview:'互動展示 · 所有帳戶、金幣及付款均為模擬',synopsis:'一段看似平凡的相遇，牽動了多年前的秘密。當愛情與真相交錯，她必須作出改變命運的選擇。',list:'選擇集數',free:'免費',locked:'120 金幣',unlocked:'已解鎖',save:'加入收藏',saved:'已收藏',play:'立即觀看',episode:'第',unit:'集',player:'示範播放器',playerNote:'目前以示範動畫展示播放操作，並非正式短劇影片。',next:'下一集',prev:'上一集',pause:'暫停',resume:'播放',sub:'字幕',signin:'登入',register:'邀請註冊',email:'電郵',password:'密碼',name:'顯示名稱',invite:'邀請碼',inviteHint:'示範邀請碼：BAYAR2026。請使用虛構資料，毋須輸入真實密碼。',authNote:'此展示版不會建立真實帳戶或傳送電郵。',account:'我的帳戶',welcome:'歡迎回來',coins:'金幣',vip:'VIP 會員',nonvip:'未開通',active:'已開通（模擬）',favorites:'我的收藏',history:'觀看歷史',orders:'訂單記錄',empty:'暫時未有記錄',logout:'登出',store:'VIP 與金幣',vipCopy:'全庫暢看 · 免廣告',month:'月費',quarter:'季費',year:'年費',renew:'訂閱方案預設續期；QPay 自動扣款能力仍待確認。',topup:'金幣儲值',coinNote:'金幣數量僅供展示，正式套餐待確認。120 金幣解鎖一集。',checkout:'訂單確認',qpay:'模擬 QPay 付款',confirm:'確認模擬付款',paymentNote:'只展示付款流程，毋須掃碼或提供付款資料。',success:'模擬付款成功',purchased:'權益已加入本次展示帳戶。',unlock:'此集需要解鎖',unlockCopy:'使用 120 金幣解鎖，或開通 VIP 暢看。',unlockButton:'用 120 金幣解鎖',insufficient:'金幣不足，請先儲值或開通 VIP。',needLogin:'請先用示範帳戶登入，繼續此操作。',invalid:'邀請碼不正確，請使用 BAYAR2026。',privacy:'私隱政策',terms:'使用條款',support:'支援中心',legal:'正式上線前會提供完整政策、付款與退款條款。展示期間請勿提交真實個人資料。',search:'搜尋劇名',browse:'探索劇庫',result:'搜尋結果',speed:'倍速',full:'全螢幕',demoName:'示範觀眾',expiry:'本次示範期間有效',auto:'VIP 示範訂閱',coinPack:'示範金幣包',status:'成功（模擬）'},
en:{back:'Back to home',preview:'Interactive preview · Accounts, coins and payments are simulated',synopsis:'An unexpected encounter reveals a secret buried for years. Caught between love and the truth, she must make a choice that changes everything.',list:'Episodes',free:'Free',locked:'120 coins',unlocked:'Unlocked',save:'Add to favorites',saved:'Saved',play:'Watch now',episode:'Episode',unit:'',player:'Demo player',playerNote:'An animated sample demonstrates playback controls. This is not a licensed drama video.',next:'Next episode',prev:'Previous',pause:'Pause',resume:'Play',sub:'Subtitles',signin:'Sign in',register:'Join by invitation',email:'Email',password:'Password',name:'Display name',invite:'Invitation code',inviteHint:'Demo code: BAYAR2026. Use fictional details and a disposable password.',authNote:'No real account is created and no email is sent.',account:'My account',welcome:'Welcome back',coins:'Coins',vip:'VIP membership',nonvip:'Not active',active:'Active (simulated)',favorites:'Favorites',history:'Watch history',orders:'Orders',empty:'Nothing here yet',logout:'Sign out',store:'VIP & coins',vipCopy:'Full library · No ads',month:'Monthly',quarter:'Quarterly',year:'Annual',renew:'Subscriptions are intended to renew. QPay recurring debit support is still to be confirmed.',topup:'Coin top-ups',coinNote:'Coin quantities are illustrative and await confirmation. Unlock one episode for 120 coins.',checkout:'Review your order',qpay:'Simulated QPay checkout',confirm:'Confirm simulated payment',paymentNote:'A preview only. No scanning or payment details required.',success:'Simulated payment successful',purchased:'Your entitlement is available in this demo session.',unlock:'Unlock this episode',unlockCopy:'Spend 120 coins or subscribe to VIP to keep watching.',unlockButton:'Unlock for 120 coins',insufficient:'Not enough coins. Top up or explore VIP.',needLogin:'Sign in with a demo account to continue.',invalid:'Use the demo invitation code BAYAR2026.',privacy:'Privacy',terms:'Terms',support:'Support',legal:'Full policies, payment and refund terms will be provided before launch. Please do not submit personal information in this preview.',search:'Search drama titles',browse:'Browse dramas',result:'Search results',speed:'Speed',full:'Fullscreen',demoName:'Demo viewer',expiry:'Valid for this demo session',auto:'Demo VIP subscription',coinPack:'Demo coin pack',status:'Successful (simulated)'},
mn:{back:'Нүүр рүү буцах',preview:'Загвар · Бүртгэл, зоос, төлбөр нь туршилтынх',synopsis:'Санаандгүй учрал олон жилийн нууцыг илчилнэ. Хайр ба үнэний дунд тэр хувь заяагаа өөрчлөх сонголт хийх ёстой.',list:'Ангиуд',free:'Үнэгүй',locked:'120 зоос',unlocked:'Нээгдсэн',save:'Хадгалах',saved:'Хадгалсан',play:'Үзэх',episode:'Анги',unit:'',player:'Туршилтын тоглуулагч',playerNote:'Энэ нь тоглуулагчийн хөдөлгөөнт загвар бөгөөд жинхэнэ драмын видео биш.',next:'Дараагийн анги',prev:'Өмнөх анги',pause:'Түр зогсоох',resume:'Тоглуулах',sub:'Хадмал',signin:'Нэвтрэх',register:'Урилгаар бүртгүүлэх',email:'И-мэйл',password:'Нууц үг',name:'Нэр',invite:'Урилгын код',inviteHint:'Туршилтын код: BAYAR2026. Зохиомол мэдээлэл ашиглана уу.',authNote:'Жинхэнэ бүртгэл үүсгэхгүй, и-мэйл илгээхгүй.',account:'Миний бүртгэл',welcome:'Тавтай морил',coins:'Зоос',vip:'VIP эрх',nonvip:'Идэвхгүй',active:'Идэвхтэй (туршилт)',favorites:'Хадгалсан',history:'Үзсэн түүх',orders:'Захиалгууд',empty:'Одоогоор хоосон',logout:'Гарах',store:'VIP ба зоос',vipCopy:'Бүх анги · Зар сурталчилгаагүй',month:'Сар',quarter:'Улирал',year:'Жил',renew:'Автомат сунгалтыг төлөвлөсөн. QPay давтан төлбөрийн боломжийг баталгаажуулна.',topup:'Зоос цэнэглэх',coinNote:'Зоосны хэмжээ нь зөвхөн жишээ. Нэг ангийг 120 зоосоор нээнэ.',checkout:'Захиалга шалгах',qpay:'QPay төлбөрийн загвар',confirm:'Туршилтын төлбөр батлах',paymentNote:'Бодит төлбөр авахгүй. Төлбөрийн мэдээлэл шаардлагагүй.',success:'Туршилтын төлбөр амжилттай',purchased:'Эрхийг энэ туршилтын бүртгэлд нэмлээ.',unlock:'Энэ ангийг нээх',unlockCopy:'120 зоос ашиглах эсвэл VIP эрх авах.',unlockButton:'120 зоосоор нээх',insufficient:'Зоос хүрэлцэхгүй. Цэнэглэх эсвэл VIP эрх авах.',needLogin:'Туршилтын бүртгэлээр нэвтэрнэ үү.',invalid:'BAYAR2026 кодыг ашиглана уу.',privacy:'Нууцлал',terms:'Нөхцөл',support:'Тусламж',legal:'Албан ёсны нээлтийн өмнө бүрэн нөхцөл, төлбөр, буцаалтын бодлогыг оруулна. Хувийн мэдээллээ бүү оруулна уу.',search:'Драмын нэрээр хайх',browse:'Драмууд',result:'Хайлтын үр дүн',speed:'Хурд',full:'Бүтэн дэлгэц',demoName:'Туршилтын үзэгч',expiry:'Энэ туршилтын хугацаанд хүчинтэй',auto:'VIP туршилтын эрх',coinPack:'Зоосны туршилтын багц',status:'Амжилттай (туршилт)'}
};
const session={user:null,coins:0,vip:false,favorites:new Set(),unlocks:new Set(),history:new Map(),orders:[]};
let page='home',currentDrama=0,currentEpisode=1,tab='favorites',authMode='register',pending=null,afterAuth=null,playing=false,progress=0,rate=1,subtitles=true,timer=null;
const surface=document.createElement('section');surface.id='experience';surface.hidden=true;document.body.append(surface);

let settings;
function syncCatalog(){const db=BayarStore.read();settings=db.prices;db.dramas.forEach((d,i)=>{dramas[i]={titles:[d.mn,d.en,d.zh],cat:['','浪漫愛情','復仇逆襲','懸疑反轉','家庭故事'].indexOf(d.category),eps:d.episodes,img:d.image,tone:'#423528',badge:'newBadge',free:d.free,published:d.published,synopsis:d.synopsis}});dramas.length=db.dramas.length;}
syncCatalog();render();
const vipPrices=()=>[settings.month,settings.quarter,settings.year];
const coinPrices=()=>[settings.p1,settings.p2,settings.p3,settings.p4];
const coinAmounts=()=>[settings.c1,settings.c2,settings.c3,settings.c4];
const freeCount=()=>dramas[currentDrama].free;
function saveSession(){if(session.user)localStorage.setItem('bayar-viewer',JSON.stringify({...session,favorites:[...session.favorites],unlocks:[...session.unlocks],history:[...session.history]}))}
function restoreSession(){try{const s=JSON.parse(localStorage.getItem('bayar-viewer'));if(s)Object.assign(session,s,{favorites:new Set(s.favorites),unlocks:new Set(s.unlocks),history:new Map(s.history)})}catch{}}
restoreSession();

const U=()=>ui[lang];const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function btn(label,action,cls='secondary',attrs=''){return `<button class="${cls}" data-flow="${action}" ${attrs}>${label}</button>`}
function shell(body){const u=U();surface.innerHTML=`<div class="flow-top"><button data-flow="home">← ${u.back}</button><a class="flow-brand" href="#home" data-flow="home">BAYAR <small>DRAMA</small></a><button data-flow="account">♙ ${u.account}</button></div><p class="demo-ribbon">${u.preview}</p><div class="flow-body">${body}</div>`}
function navigate(next){clearInterval(timer);playing=false;page=next;surface.hidden=next==='home';document.querySelector('main').hidden=next!=='home';document.querySelector('.header').hidden=next!=='home';document.querySelector('footer').hidden=next!=='home';if(next!=='home')draw();window.scrollTo(0,0)}
function entitled(){return currentEpisode<=freeCount()||session.vip||session.unlocks.has(`${currentDrama}:${currentEpisode}`)}
function episodeButtons(){return `<div class="episode-grid">${Array.from({length:dramas[currentDrama].eps},(_,i)=>{const n=i+1,open=n<=freeCount()||session.vip||session.unlocks.has(`${currentDrama}:${n}`);return `<button data-flow="episode" data-episode="${n}" class="${n===currentEpisode?'selected':''} ${open?'available':''}"><b>${String(n).padStart(2,'0')}</b><small>${n<=freeCount()?U().free:open?U().unlocked:'🔒'}</small></button>`}).join('')}</div>`}
function draw(){const u=U(),d=dramas[currentDrama];u.unlockButton=lang==='zh'?`用 ${settings.unlock} 金幣解鎖`:`${settings.unlock} ${u.coins}`;u.unlockCopy=lang==='zh'?`使用 ${settings.unlock} 金幣解鎖，或開通 VIP 暢看。`:u.unlockButton;u.coinNote=lang==='zh'?`金幣數量暫定，每集 ${settings.unlock} 金幣。`:u.coinNote;
 if(page==='detail'){shell(`<div class="detail-layout"><div class="detail-art"><img src="https://images.unsplash.com/${d.img}?auto=format&fit=crop&w=650&q=85" alt="${esc(titleOf(d))}"><span>BAYAR COLLECTION</span></div><div class="detail-copy"><span class="section-kicker">BAYAR COLLECTION</span><h1>${titleOf(d)}</h1><p class="detail-meta">${text[lang].cats[d.cat]} · ${d.eps} ${text[lang].unit} · 16+</p><p>${esc(lang==='zh'&&d.synopsis?d.synopsis:u.synopsis)}</p><div class="flow-actions">${btn('▶ '+u.play,'play','primary')}${btn(session.favorites.has(currentDrama)?'♥ '+u.saved:'♡ '+u.save,'favorite')}</div><p class="gold">${lang==='zh'?`首 ${freeCount()} 集免費`:freeCount()+' · '+u.free}</p><h2>${u.list}</h2>${episodeButtons()}</div></div>`)}
 else if(page==='player'){if(!entitled()){drawUnlock();return}session.history.set(currentDrama,{episode:currentEpisode,progress});saveSession();shell(`<div class="player-layout"><div><div class="video-stage" id="videoStage"><div class="sample-scene"><img src="https://images.unsplash.com/${d.img}?auto=format&fit=crop&w=900&q=85" alt=""><div class="scene-light"></div><span class="scene-brand">BAYAR DRAMA</span><div class="scene-caption">${titleOf(d)}<small>${u.episode} ${currentEpisode} ${u.unit}</small></div><p id="sampleSubtitle">${subtitles?u.synopsis.split('.')[0]:''}</p><button class="big-play" data-flow="toggle">▶</button></div><div class="video-controls"><input id="seek" aria-label="Playback progress" type="range" min="0" max="100" value="${progress}"><div>${btn(u.resume,'toggle','text-button','id="playToggle"')}<span id="timeText">${Math.round(progress*1.2)} / 120s</span><select id="rate" aria-label="${u.speed}"><option value="1">1×</option><option value="1.5">1.5×</option><option value="2">2×</option></select>${btn(u.sub,'subtitle','text-button')}${btn('⛶','fullscreen','text-button',`aria-label="${u.full}"`)}</div></div></div><p class="muted player-disclaimer">${u.playerNote}</p><div class="flow-actions">${btn('← '+u.prev,'previous')}${btn(u.next+' →','next','primary')}</div></div><aside><span class="section-kicker">${u.player}</span><h2>${titleOf(d)}</h2><p class="gold">${u.episode} ${currentEpisode} ${u.unit}</p><h3>${u.list}</h3>${episodeButtons()}</aside></div>`)}
 else if(page==='auth'){shell(`<div class="auth-card"><span class="section-kicker">BAYAR DRAMA</span><h1>${authMode==='register'?u.register:u.signin}</h1><div class="account-tabs">${btn(u.register,'register',authMode==='register'?'active':'')}${btn(u.signin,'signin',authMode==='signin'?'active':'')}</div><p class="muted">${u.inviteHint}</p><form id="authForm">${authMode==='register'?`<label>${u.name}<input name="name" required maxlength="40" placeholder="${u.demoName}"></label><label>${u.invite}<input name="invite" required value="BAYAR2026" autocomplete="off"></label>`:''}<label>${u.email}<input name="email" type="email" required placeholder="viewer@example.com" autocomplete="off"></label><label>${u.password}<input name="password" type="password" required minlength="6" autocomplete="off" placeholder="••••••••"></label><p id="authError" role="alert"></p><button class="primary" type="submit">${authMode==='register'?u.register:u.signin} →</button></form><p class="muted">${u.authNote}</p></div>`)}
 else if(page==='store'){shell(`<div class="store-heading"><span class="section-kicker gold">BAYAR MEMBERSHIP</span><h1>${u.store}</h1><p>${u.vipCopy}</p></div><div class="plans">${vipPrices().map((price,i)=>`<div class="plan ${i===1?'recommended':''}"><span class="gold">♛ VIP</span><h2>${[u.month,u.quarter,u.year][i]}</h2><p class="price">${price.toLocaleString()} <small>₮</small></p>${btn(text[lang].vipButton,'buyvip','primary',`data-index="${i}"`)}</div>`).join('')}</div><p class="muted">${u.renew}</p><h2>${u.topup}</h2><p class="muted">${u.coinNote}</p><div class="coin-plans">${coinPrices().map((price,i)=>`<button data-flow="buycoins" data-index="${i}"><span class="coin-symbol">◈</span><strong>${coinAmounts()[i].toLocaleString()} ${u.coins}</strong><span>${price.toLocaleString()} ₮</span></button>`).join('')}</div>`)}
 else if(page==='checkout'){shell(`<div class="checkout-card"><span class="section-kicker">QPAY · DEMO</span><h1>${u.checkout}</h1><div class="order-summary"><h2>${pending.label}</h2><strong>${pending.price.toLocaleString()} ₮</strong></div><div class="mock-pay"><span>QPay</span><p>${u.qpay}</p><span class="mock-seal">DEMO</span></div><p class="muted">${u.paymentNote}</p>${btn(u.confirm,'pay','primary')}</div>`)}
 else if(page==='success'){shell(`<div class="checkout-card"><div class="success-icon">✓</div><h1>${u.success}</h1><p>${u.purchased}</p><p class="gold">${pending.label} · ${pending.price.toLocaleString()} ₮</p>${btn(u.account,'account','primary')}${btn(u.play,'play')}</div>`)}
 else if(page==='account'){if(!session.user){afterAuth='account';navigate('auth');return}let body='';if(tab==='orders')body=session.orders.length?session.orders.map(o=>`<div class="order-row"><div><strong>${o.label}</strong><small>${o.id} · ${o.time}</small></div><div>${o.price.toLocaleString()} ₮<small>${u.status}</small></div></div>`).join(''):`<p class="muted">${u.empty}</p>`;else {const ids=tab==='favorites'?[...session.favorites]:[...session.history.keys()];body=ids.length?`<div class="account-grid">${ids.map(i=>`<div>${card(dramas[i],i)}${tab==='history'?`<p class="muted">${u.episode} ${session.history.get(i).episode} · ${Math.round(session.history.get(i).progress)}%</p>`:''}</div>`).join('')}</div>`:`<p class="muted">${u.empty}</p>`}shell(`<div class="profile-heading"><div class="avatar">B</div><div><p class="muted">${u.welcome}</p><h1>${esc(session.user.name)}</h1><p class="muted">${esc(session.user.email)}</p></div>${btn(u.logout,'logout','text-button')}</div><div class="account-stats"><div><small>${u.coins}</small><strong>${session.coins}</strong>${btn(u.topup,'store','text-button')}</div><div><small>${u.vip}</small><strong>${session.vip?u.active:u.nonvip}</strong><span class="muted">${session.vip?u.expiry:''}</span>${btn(text[lang].vipButton,'store','text-button')}</div></div><div class="account-tabs">${['favorites','history','orders'].map(t=>btn(u[t],'tab',tab===t?'active':'',`data-tab="${t}"`)).join('')}</div>${body}`)}
 else if(page==='browse'){shell(`<h1>${u.browse}</h1><label class="search-box"><span>⌕</span><input id="dramaSearch" type="search" placeholder="${u.search}" aria-label="${u.search}"></label><div id="searchResults" class="account-grid">${dramas.filter(d=>d.published!==false).map(card).join('')}</div>`)}
 else {shell(`<div class="auth-card"><h1>${u[page]||page}</h1><p>${u.legal}</p></div>`)}
}
function drawUnlock(){shell(`<div class="checkout-card"><span class="section-kicker">${titleOf(dramas[currentDrama])} · ${U().episode} ${currentEpisode}</span><h1>♛ ${U().unlock}</h1><p>${U().unlockCopy}</p><p class="gold">${U().coins}: ${session.coins}</p><p id="unlockError" role="alert"></p><div class="flow-actions">${btn(U().unlockButton,'unlock','primary')}${btn(text[lang].vipButton,'store')}${btn(U().topup,'store')}</div></div>`)}
function requireUser(next){if(session.user)return true;afterAuth=next;authMode='register';navigate('auth');return false}
function goPlay(){if(currentEpisode>freeCount()&&!requireUser('player'))return;progress=session.history.get(currentDrama)?.episode===currentEpisode?session.history.get(currentDrama).progress:0;navigate('player')}
function action(a,el){const u=U();switch(a){
case 'home':navigate('home');break;
case 'detail':navigate('detail');break;
case 'play':goPlay();break;
case 'episode':currentEpisode=+el.dataset.episode;goPlay();break;
case 'next':if(currentEpisode<dramas[currentDrama].eps){currentEpisode++;goPlay()}break;
case 'previous':if(currentEpisode>1){currentEpisode--;goPlay()}break;
case 'favorite':if(!requireUser('detail'))break;session.favorites.has(currentDrama)?session.favorites.delete(currentDrama):session.favorites.add(currentDrama);saveSession();draw();break;
case 'register':case 'signin':authMode=a;navigate('auth');break;
case 'account':navigate('account');break;
case 'tab':tab=el.dataset.tab;draw();break;
case 'logout':localStorage.removeItem('bayar-viewer');session.user=null;session.coins=0;session.vip=false;session.favorites.clear();session.history.clear();session.unlocks.clear();session.orders=[];navigate('home');break;
case 'store':navigate('store');break;
case 'buyvip':{const i=+el.dataset.index;pending={type:'vip',price:vipPrices()[i],label:`VIP · ${[u.month,u.quarter,u.year][i]}`};if(requireUser('checkout'))navigate('checkout');break;}
case 'buycoins':{const i=+el.dataset.index;pending={type:'coins',price:coinPrices()[i],amount:coinAmounts()[i],label:`${u.coinPack} · ${coinAmounts()[i]} ${u.coins}`};if(requireUser('checkout'))navigate('checkout');break;}
case 'pay':if(!pending||page!=='checkout')break;if(pending.type==='vip')session.vip=true;else session.coins+=pending.amount;session.orders.unshift({...pending,id:'DEMO-'+String(session.orders.length+1).padStart(4,'0'),time:new Date().toLocaleString()});BayarStore.update(db=>db.orders.unshift({id:'DEMO-'+Date.now(),email:session.user.email,product:pending.label,amount:pending.price,status:'成功',time:new Date().toLocaleString()}));saveSession();navigate('success');break;
case 'unlock':if(!requireUser('player'))break;if(session.coins<settings.unlock){document.getElementById('unlockError').textContent=u.insufficient;break}session.coins-=settings.unlock;session.unlocks.add(`${currentDrama}:${currentEpisode}`);saveSession();navigate('player');break;
case 'toggle':playing=!playing;document.querySelector('.sample-scene').classList.toggle('playing',playing);document.getElementById('playToggle').textContent=playing?u.pause:u.resume;document.querySelector('.big-play').textContent=playing?'Ⅱ':'▶';clearInterval(timer);if(playing)timer=setInterval(()=>{progress=Math.min(100,progress+rate/1.2);document.getElementById('seek').value=progress;document.getElementById('timeText').textContent=`${Math.round(progress*1.2)} / 120s`;session.history.set(currentDrama,{episode:currentEpisode,progress});saveSession();if(progress>=100){clearInterval(timer);playing=false;document.getElementById('playToggle').textContent=u.resume;document.querySelector('.big-play').textContent='▶';document.querySelector('.sample-scene').classList.remove('playing')}},1000);break;
case 'subtitle':subtitles=!subtitles;document.getElementById('sampleSubtitle').textContent=subtitles?u.synopsis:'';break;
case 'fullscreen':{const v=document.getElementById('videoStage');if(document.fullscreenElement)document.exitFullscreen?.();else v.requestFullscreen?.().catch(()=>{});break;}
}}
document.addEventListener('click',e=>{const flow=e.target.closest('[data-flow]');const dr=e.target.closest('[data-drama]');const old=e.target.closest('[data-action]');const browse=e.target.closest('a[href="#library"],a[href="#new"]');const homeLink=e.target.closest('a[href="#home"]');if(homeLink&&page!=='home'){e.preventDefault();e.stopImmediatePropagation();navigate('home');return;}if(!flow&&!dr&&!old&&!browse)return;if(old&&!['vip','invite','watch','detail','support','privacy','terms'].includes(old.dataset.action))return;e.preventDefault();e.stopImmediatePropagation();if(dialog.open)dialog.close();if(flow){action(flow.dataset.flow,flow);return}if(dr){currentDrama=+dr.dataset.drama;currentEpisode=session.history.get(currentDrama)?.episode||1;navigate('detail');return}if(browse){navigate('browse');return}const a=old.dataset.action;if(a==='vip')navigate('store');else if(a==='invite'){navigate(session.user?'account':'auth')}else if(a==='watch'||a==='detail'){currentDrama=hero;currentEpisode=1;if(a==='watch')goPlay();else navigate('detail')}else navigate(a)},true);
document.addEventListener('submit',e=>{if(e.target.id!=='authForm')return;e.preventDefault();const f=new FormData(e.target);if(authMode==='register'&&settings.registration==='invite'){const db=BayarStore.read(),code=String(f.get('invite')).trim().toUpperCase(),email=String(f.get('email')).trim().toLowerCase();const invite=db.invites.find(i=>i.code===code&&i.status==='可使用'&&i.expiry>=new Date().toISOString().slice(0,10)&&(i.code==='BAYAR2026'||i.email.toLowerCase()===email));if(!invite){document.getElementById('authError').textContent='邀請碼無效、已過期，或電郵不符。';return}invite.status='已使用';BayarStore.save(db)}session.user={name:String(f.get('name')||U().demoName),email:String(f.get('email'))};e.target.reset();saveSession();const next=afterAuth||'account';afterAuth=null;navigate(next)});
document.addEventListener('input',e=>{if(e.target.id==='seek'){progress=+e.target.value;document.getElementById('timeText').textContent=`${Math.round(progress*1.2)} / 120s`;session.history.set(currentDrama,{episode:currentEpisode,progress})}if(e.target.id==='dramaSearch'){const q=e.target.value.toLocaleLowerCase();const matches=dramas.filter(d=>d.published!==false&&d.titles.some(t=>t.toLocaleLowerCase().includes(q)));document.getElementById('searchResults').innerHTML=matches.length?matches.map(card).join(''):`<p class="muted">${U().empty}</p>`}});
document.addEventListener('change',e=>{if(e.target.id==='rate')rate=+e.target.value;if(e.target.id==='language'&&page!=='home')draw()});


window.addEventListener('storage',()=>{syncCatalog();render();if(page!=='home'&&page!=='checkout')draw()});window.addEventListener('focus',()=>{syncCatalog();render();if(page!=='home'&&page!=='checkout')draw()});

